### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [mhtvsSFrpHdE/obsidian-todo#1]
- [x] As obsidian launcher, OS startup item 06e7e7b1af8012d1bd91b6316329c537014bab6f
- [x] Open different page by day of week 417297d12b679a31a5013f330397f54ef37cb023
- [x] Reset "every day" page checkbox status on first time in a day d3f605971191e4eca7a1ced1115f824d7357249b
